### ISSUE TITLE
PH315-52 Kernel panic

### ISSUE THREAD

**Issue by ramonssouza** [JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module#52]
What Linux distribution do you use? I can't use it on Manjaro and Fedora 36

**Comment by ramonssouza** [comment]
![Uploading IMG_20220708_235532.jpg…]()

**Comment by ramonssouza** [comment]
![IMG_20220708_235532](https://user-images.githubusercontent.com/54721978/178089285-8426eb2e-ce4b-4e38-84ac-68c76770e629.jpg)

**Comment by ramonssouza** [comment]
opensuse tumbleweed working perfectly fine

**Comment by JafarAkhondali** [comment]
@ramonssouza I'm using Pop-os as it works out of the box with Nvidia graphic cards.

**Comment by ramonssouza** [comment]
Happens with pop-os 22.04 too, when I turn off the notebook this problem appears

**Comment by wagyourtail** [comment]
I've had this as well on Arch (I also have a ph315-52) didn't realize it was caused by this...
doesn't really inconvenience me too much, I just hard power off when it comes up because it only happens when I'm shutting down the system anyway.

**Comment by JafarAkhondali** [comment]
I can't debug it as I don't own my Acer Predator anymore(physical damage). Hope someone else can work on this

**Comment by ramonssouza** [comment]
I tested on artix linux with openrc and it seems to work without problems

**Comment by ramonssouza** [comment]
Will agum error with systemd service?

**Comment by ramonssouza** [comment]
Is there any news regarding this bug?

**Comment by x211321** [comment]
I’m running the module on a Nitro AN515-45 (4 RGB zones / no turbo). The module worked well with my previous Linux Mint setup (besides the static RGB mode not working). 

A couple of days ago I switched to fedora 36 and now I’m experiencing what I assume to be this exact issue: sporadic kernel panic during shutdown (though on the bright side the static mode is now working).

uname -r
`5.19.16-200.fc36.x86_64`

Since I know nothing about the development and debugging of kernel modules I poked around the script files and started to wonder whether the unloading of the `facer` module during `ExecStop` and the subsequent reload of the `acer_wmi` module could be the cause of this problem.

So I removed the `ExecStop` key from the service configuration and now the issue seems to be gone. Before the change I had kernel panics roughly every second or third reboot. Now after roughly 20 reboots not a single panic occurred. 

Of course this could just be coincidence but maybe its a clue to what is happening. Maybe someone else could try those steps and check if the behavior is reproducible for them.

**Steps I took:**
1) check out the repo
2) If the module/service is already installed run: `uninstall_service.sh`
3) Remove the line `ExecStop=/bin/bash ./uninstall.sh` from  `install_service.sh`
4) Run `install_service.sh`
5) If SELinux protection is active (fedora default) run:

`semanage fcontext -a -t object_r /opt/turbo-fan/src/facer.ko`
`chcon -t modules_object_t /opt/turbo-fan/src/facer.ko`

Otherwise the install script run by systemd cannot access the module.

**Alternatively if everything is already set up and working:**
Removing the `ExecStop` key from `/etc/systemd/system/turbo-fan.service` should have the same effect.

Of course once those modifications have been made `systemctl stop turbo-fan.service` will no longer have any effect. To restore the stock `acer_wmi` module you could either run `/opt/turbo-fan/uninstall.sh` or `rmmod facer` and `modprobe acer_wmi` manually.

Again I have no idea if this is actually the cause of this issue but to me it appears as if the kernel is simply unhappy to have those two modules switched during shutdown.

**Comment by JafarAkhondali** [comment]
Can someone verify @x211321 solution?

**Comment by ramonssouza** [comment]
I'll test it on my notebook, thanks in advance for the help

**Comment by ramonssouza** [comment]
It seems to work fine now. Thanks!

**Comment by pratyush3757** [comment]
The fix mentioned by @x211321 works for me too. I tried it on PH315-52, Manjaro, one month ago. And didn't have any panics during shutdown/reboot since.
